# Generated by Django 5.1.3 on 2024-11-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulgarian_meteo_pro", "0002_bulgarianmeteoprodata_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulgarianmeteoprodata",
            options={"ordering": ["recorded_at"]},
        ),
        migrations.RemoveIndex(
            model_name="bulgarianmeteoprodata",
            name="bulgarian_m_city_4a8380_idx",
        ),
        migrations.RenameField(
            model_name="bulgarianmeteoprodata",
            old_name="timestamp",
            new_name="recorded_at",
        ),
        migrations.RenameField(
            model_name="bulgarianmeteoprodata",
            old_name="station_id",
            new_name="station_identifier",
        ),
        migrations.RemoveField(
            model_name="bulgarianmeteoprodata",
            name="station_status",
        ),
        migrations.AddField(
            model_name="bulgarianmeteoprodata",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("operational", "Operational"),
                    ("maintenance", "Maintenance"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                default="operational",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="bulgarianmeteoprodata",
            index=models.Index(
                fields=["city", "recorded_at"], name="bulgarian_m_city_54342d_idx"
            ),
        ),
    ]
