# Generated by Django 5.1.3 on 2024-11-08 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Readings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp_fahrenheit", models.FloatField()),
                ("humidity_percent", models.FloatField()),
                ("pressure_hpa", models.FloatField()),
                ("uv_index", models.IntegerField()),
                ("rain_mm", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=100)),
                (
                    "coordinates",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_master_x.coordinates",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherMasterXData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("station_identifier", models.CharField(max_length=50)),
                ("city", models.CharField(editable=False, max_length=100)),
                ("recorded_at", models.DateTimeField()),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_master_x.location",
                    ),
                ),
                (
                    "readings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_master_x.readings",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["city", "recorded_at"],
                        name="weather_mas_city_0c0ed9_idx",
                    )
                ],
            },
        ),
    ]
