# Generated by Django 5.1.3 on 2024-11-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather_master_x", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weathermasterxdata",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="weathermasterxdata",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("operational", "Operational"),
                    ("maintenance", "Maintenance"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                max_length=20,
            ),
        ),
    ]
